### PR TITLE
Add tags to MapRowTarget within API

### PR DESCRIPTION
**Pull request by johngrimes**
## Description

This change adds a set of tag strings to the `MapRowTarget` resource. The intent is that this generic capability will be able to be used for a range of different user-facing features within the UI.

You can retrieve a list of `MapRowTarget` resources, including their tags, using the following request:

```
GET /mapRowTargets
```

```json
{
  "_embedded": {
    "mapRowTargets": [
      {
        "created": "2022-12-14T08:16:53.816302Z",
        "modified": "2022-12-14T08:16:53.816302Z",
        "createdBy": "ef3f9b67-2898-4799-8252-35dd7ee0f940",
        "modifiedBy": "ef3f9b67-2898-4799-8252-35dd7ee0f940",
        "id": 1,
        "targetCode": "328432000",
        "targetDisplay": "Adrenoleukodystrophy food (product)",
        "relationship": "TARGET_INEXACT",
        "tags": [],
        "flagged": false,
        "_links": {
          "self": {
            "href": "http://localhost:8080/mapRowTargets/1"
          },
          "mapRowTarget": {
            "href": "http://localhost:8080/mapRowTargets/1{?projection}",
            "templated": true
          },
          "row": {
            "href": "http://localhost:8080/mapRowTargets/1/row{?projection}",
            "templated": true
          }
        }
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/mapRowTargets"
    },
    "profile": {
      "href": "http://localhost:8080/profile/mapRowTargets"
    },
    "search": {
      "href": "http://localhost:8080/mapRowTargets/search"
    }
  },
  "page": {
    "size": 20,
    "totalElements": 1,
    "totalPages": 1,
    "number": 0
  }
}
```

Then you can update a `MapRowTarget` with a new set of tags:

```
PUT /mapRowTargets/1
```

```json
{
  "id": 1,
  "targetCode": "328432000",
  "targetDisplay": "Adrenoleukodystrophy food (product)",
  "relationship": "TARGET_INEXACT",
  "tags": [
    "foo",
    "bar"
  ],
  "flagged": false
}
```

And see those new tags reflected back in the retrieved resources:

```
GET /mapRowTargets
```

```json
{
  "_embedded": {
    "mapRowTargets": [
      {
        "created": "2022-12-14T08:16:53.816302Z",
        "modified": "2022-12-14T08:23:39.973759Z",
        "createdBy": "ef3f9b67-2898-4799-8252-35dd7ee0f940",
        "modifiedBy": "ef3f9b67-2898-4799-8252-35dd7ee0f940",
        "id": 1,
        "targetCode": "328432000",
        "targetDisplay": "Adrenoleukodystrophy food (product)",
        "relationship": "TARGET_INEXACT",
        "tags": [
          "bar",
          "foo"
        ],
        "flagged": false,
        "_links": {
          "self": {
            "href": "http://localhost:8080/mapRowTargets/1"
          },
          "mapRowTarget": {
            "href": "http://localhost:8080/mapRowTargets/1{?projection}",
            "templated": true
          },
          "row": {
            "href": "http://localhost:8080/mapRowTargets/1/row{?projection}",
            "templated": true
          }
        }
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/mapRowTargets"
    },
    "profile": {
      "href": "http://localhost:8080/profile/mapRowTargets"
    },
    "search": {
      "href": "http://localhost:8080/mapRowTargets/search"
    }
  },
  "page": {
    "size": 20,
    "totalElements": 1,
    "totalPages": 1,
    "number": 0
  }
}
```

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- `MapRowTargetResourceIT#shouldUpdateAndRetrieveMapRowTargetTags`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Comment by johngrimes** [comment]
Is there any API documentation?

Do we have a Postman collection?

**Comment by lawley** [comment]
I have updated the JIRA issue with what I think are the missing details :-)
Bottom line, I don't think we're there yet.

What I added was:
* need "add tag" and "remove tag" APIs
* need Tag support for MapRow, not just MapRowTarget

**Comment by johngrimes** [comment]
@developerdu I've made it possible to query the number of map row targets with a particular tag.

You can make a request like this:

```
GET /mapRowTargets?tags=foo
```

The number of matching map row targets is in `page.totalElements`.

**Comment by johngrimes** [comment]
I've made a few changes:

- Updated the target code validation process that gets triggered when creating a new version so that it uses tags, instead of the flag
- Added a search parameter to `mapRowTargets` so that you can do something like this: `GET /mapRowTargets?mapId=1&tags=target-out-of-scope`
- Removed updated to `modified` and `modifiedBy` for updates that only concern tags
- Updated the "map view" to include tags - I think this is important for parts of the UI
- Updated the tests

Important note: this solution does not work on H2, as it uses [INSERT IGNORE](https://dev.mysql.com/doc/refman/8.0/en/insert.html). I think the plan is to remove H2 from our development environments and replace it with MariaDB/MySQL. I don't think it is a dependency of the tests any longer, they spin up a MySQL container.

Still to do:

- [ ] Remove the flag
- [ ] Remove H2 migrations and dependency

**Pull request merged**
